### ISSUE TITLE
[Bug] No wavy reflections at beach

### ISSUE THREAD

**Issue by NightFright2k19** [Floogen/DynamicReflections#10]
With target location set to "Default", wavy reflections won't work at the beach. They work anywhere else, though (tested in Mountains, Town).

**Comment by NightFright2k19** [comment]
Seems this is intended after getting forum feedback.

**Comment by Floogen** [comment]
This is indeed intended, though you can still set the beach to have a wavy effect by disabling the override or setting "Enable Wavy Reflections" within the beach override.
