### ISSUE TITLE
[Bug/Feature] NPC reflections during Dance of the Moonlight Jellies

### ISSUE THREAD

**Issue by NightFright2k19** [Floogen/DynamicReflections#20]
There are no NPC reflections shown at the beach during the Dance of the Moonlight Jellies.

**Comment by NightFright2k19** [comment]
Related to the other issue (NPC reflections are currently N/A).

**Comment by Floogen** [comment]
Only wavy NPC reflections are disabled. Do non-wavy NPC reflections not show at all during the Dance of the Moonlight Jellies?

**Comment by NightFright2k19** [comment]
Indeed, NPC reflections actually aren't showing up at all. Forgot that this issue wasn't about wavy reflections.
Player and sky reflections work, btw.
