### ISSUE TITLE
[NPC] No wavy NPC reflections

### ISSUE THREAD

**Issue by NightFright2k19** [Floogen/DynamicReflections#21]
At least at the Ginger Island Docks (IslandSouth), it is not possible to activate wavy reflections for NPCs, even if IslandSouth and "Override default settings" is selected when choosing wavy reflections in the menu.

**Comment by Floogen** [comment]
Since v1.2.1, NPC wavy reflections have been temporarily disabled.

**Comment by NightFright2k19** [comment]
Ah right, forgot about it... So let's hope there's going to be a fix for it!
