### ISSUE TITLE
[Bug] Discoloration of water in desert/island

### ISSUE THREAD

**Issue by NightFright2k19** [Floogen/DynamicReflections#27]
At least in fall season (playing that now), water on the farm and on Ginger Island is purple and the lake in the desert is black.
This might be due to a combination with some other mod I have installed which still needs to be investigated.
![purple_farm](https://user-images.githubusercontent.com/54737241/180174070-3612d554-6200-4539-8c0b-a66f96aa503d.png)
![black_desert](https://user-images.githubusercontent.com/54737241/180174061-40f9af1d-96f9-47de-8c2e-021780b4021f.png)
![purple_island](https://user-images.githubusercontent.com/54737241/180174066-4fd66bd7-65bf-434c-abd2-92844f50456f.png)

**Comment by NightFright2k19** [comment]
Update:
Seems it has to do something with NPC reflections. If I turn them off in the default settings, water color becomes normal - however only as long as the player character does not approach the water. If it gets closer, as soon as a reflection is supposed to be drawn (or before it's about to), water color switches again - returning back to normal as soon as you back off and so on, like a switch.

Sky reflections or wavy animations don't seem to have any impact. Basically it's impossible to get a reflection with a normally colored water surface, at least in the areas I mentioned.

**Comment by Floogen** [comment]
Have you been able to replicate this with just SMAPI + Dynamic Reflections? Thus far I have not been able to.

**Comment by NightFright2k19** [comment]
I just tested it with this minimal configuration:
- SMAPI
- Dynamic Reflections v1.3.2

The problem still exists like that, even with all the other mods that I am normally using out of the way. I don't think that providing my config file helps much since I pretty much use the default settings, besides also using wavy reflections. Anyway, I tried deleting the config file and let the game generate a new one, same thing.

The issue disappears partially when deactivating NPC relections (behavior as described above, discoloration as soon as you approach water) and completely when turning off water reflections in general.

Maybe it also depends on a game setting, but tbh I wouldn't be able to guess which one it could be right now. My graphics settings are like this:
- Window Mode: Windowed Borderless
- VSync: On
- Lighting Quality: High

**Comment by Floogen** [comment]
I have pinpointed the issue. My default testing suite was using SMAPI + Dynamic Reflections + Visible Fish. When removing the latter, I can replicate your issue.

It seems to be tied to my compatibility patch for Visible Fish, so I'll need to investigate further. Thank you for the help in pinpointing this issue.

**Comment by NightFright2k19** [comment]
Excellent! Fingers crossed it can be solved soon since this is a quite annoying glitch.

**Comment by Floogen** [comment]
This should be fixed with v1.3.4!
